#!/bin/bash

# Simple deploy script
# Usage: ./deploy-simple.sh

echo "🚀 Starting deployment..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SERVER_USER="root"
SERVER_HOST="144.31.165.36"
SERVER_PATH="/var/www/telegram-catalog"
GIT_REPO="https://github.com/sberiq/telegram-catalog.git"
DOMAIN="superpuperkrutoi.ru"

echo -e "${BLUE}🔧 Configuration:${NC}"
echo -e "   Server: $SERVER_USER@$SERVER_HOST"
echo -e "   Path: $SERVER_PATH"
echo -e "   Repo: $GIT_REPO"
echo -e "   Domain: $DOMAIN"
echo ""

echo -e "${YELLOW}📝 Manual deployment steps:${NC}"
echo -e "${BLUE}1. Connect to server:${NC}"
echo -e "   ssh $SERVER_USER@$SERVER_HOST"
echo -e "   Password: HTZhvgJPd55L"
echo ""
echo -e "${BLUE}2. Run these commands on the server:${NC}"
echo ""
echo -e "${GREEN}# Create directory${NC}"
echo -e "mkdir -p $SERVER_PATH"
echo ""
echo -e "${GREEN}# Clone/update repository${NC}"
echo -e "cd $(dirname $SERVER_PATH)"
echo -e "if [ -d '$(basename $SERVER_PATH)/.git' ]; then"
echo -e "    cd $(basename $SERVER_PATH) && git pull origin main"
echo -e "else"
echo -e "    git clone $GIT_REPO $(basename $SERVER_PATH)"
echo -e "fi"
echo ""
echo -e "${GREEN}# Install dependencies${NC}"
echo -e "cd $SERVER_PATH && npm install --production"
echo ""
echo -e "${GREEN}# Create logs directory${NC}"
echo -e "mkdir -p $SERVER_PATH/logs"
echo ""
echo -e "${GREEN}# Start application${NC}"
echo -e "cd $SERVER_PATH"
echo -e "if pm2 list | grep -q telegram-catalog; then"
echo -e "    pm2 restart telegram-catalog"
echo -e "else"
echo -e "    pm2 start ecosystem.config.js"
echo -e "    pm2 save"
echo -e "fi"
echo ""
echo -e "${GREEN}# Configure Nginx${NC}"
echo -e "sudo tee /etc/nginx/sites-available/telegram-catalog > /dev/null <<EOF"
echo -e "server {"
echo -e "    listen 80;"
echo -e "    server_name $DOMAIN www.$DOMAIN;"
echo -e "    "
echo -e "    location / {"
echo -e "        proxy_pass http://localhost:3000;"
echo -e "        proxy_http_version 1.1;"
echo -e "        proxy_set_header Upgrade \\\$http_upgrade;"
echo -e "        proxy_set_header Connection 'upgrade';"
echo -e "        proxy_set_header Host \\\$host;"
echo -e "        proxy_set_header X-Real-IP \\\$remote_addr;"
echo -e "        proxy_set_header X-Forwarded-For \\\$proxy_add_x_forwarded_for;"
echo -e "        proxy_set_header X-Forwarded-Proto \\\$scheme;"
echo -e "        proxy_cache_bypass \\\$http_upgrade;"
echo -e "        proxy_read_timeout 86400;"
echo -e "    }"
echo -e "}"
echo -e "EOF"
echo ""
echo -e "${GREEN}# Activate site${NC}"
echo -e "sudo ln -sf /etc/nginx/sites-available/telegram-catalog /etc/nginx/sites-enabled/"
echo -e "sudo rm -f /etc/nginx/sites-enabled/default"
echo -e "sudo nginx -t"
echo -e "sudo systemctl restart nginx"
echo ""
echo -e "${GREEN}# Check status${NC}"
echo -e "pm2 status telegram-catalog"
echo ""
echo -e "${BLUE}3. After deployment, configure DNS:${NC}"
echo -e "   Point $DOMAIN to $SERVER_HOST"
echo ""
echo -e "${BLUE}4. Setup SSL (optional):${NC}"
echo -e "   sudo certbot --nginx -d $DOMAIN -d www.$DOMAIN"